### ISSUE TITLE
Project Creation: "Specified path is not valid..." error message

### ISSUE THREAD

**Issue by Pendrokar** [Unity3D-Wine-Support/Unity3D-on-Wine#11]
When trying to create a project with a seemingly valid path a dialog pops up stating "Specified path is not valid..." disallowing creation of a new project.

Bug report on WineHQ - http://bugs.winehq.org/show_bug.cgi?id=26272

**Comment by Pendrokar** [comment]
"Anastasius Focht" claims version 1.7.34 includes this patch, which fixes this issue.
https://bugs.winehq.org/show_bug.cgi?id=36964

**Comment by DoctorJellyface** [comment]
HECK YEAH

**Comment by DoctorJellyface** [comment]
Two weeks. Damn. I'm so sorry. I had most of those commits laying on my laptop all that time, but I just didn't have the time to even look at my laptop, let alone finish the changes and push them to the repo. Egh, I don't want to have another two weeks like those.

Sorry again.
