### ISSUE TITLE
License window crashes

### ISSUE THREAD

**Issue by Pendrokar** [Unity3D-Wine-Support/Unity3D-on-Wine#13]
Unity crashes when starting it for the first time.

WineHQ bug report - http://bugs.winehq.org/show_bug.cgi?id=36964

**Comment by Pendrokar** [comment]
"Anastasius Focht" claims version 1.7.34 includes this patch, which fixes this issue.
https://bugs.winehq.org/show_bug.cgi?id=36964

**Comment by DoctorJellyface** [comment]
This is superb. I'll update the script to suit it hopefully tommorow, along with an update to 4.6.1.

**Comment by DoctorJellyface** [comment]
Damn, didn't get to it today, even though it was near the top of my todo list. Tomorrow.
