### ISSUE TITLE
Unity window is all in plain gray color.

### ISSUE THREAD

**Issue by Pendrokar** [Unity3D-Wine-Support/Unity3D-on-Wine#16]
When opening Unity, its dashboard is all gray.
Related Wine bugs:
[Brazilian timezones are not correctly detected](http://bugs.winehq.org/show_bug.cgi?id=32916)
[Unity Indie Trial Editor window contents not drawn](http://bugs.winehq.org/show_bug.cgi?id=18061) (this may be a different issue, but with same results)

**Comment by Gousenfire** [comment]
How do I solve this problem on OpenSUSE 13.2 ? I'm using Gnome 3

**Comment by DoctorJellyface** [comment]
Settings -> Date and Time. Trying turning on/off Automatic time zone. If you have it off, you can change the time zone manually.
