### ISSUE TITLE
Unity Editor has no visible text

### ISSUE THREAD

**Issue by Pendrokar** [Unity3D-Wine-Support/Unity3D-on-Wine#18]
Unity Editor launches, but after the license window and project creation window comes the main window, which has no text in inner windows with the exceotio of the title bar.

**Comment by Pendrokar** [comment]
User "Feetsalot" of Unity Answers fixed the problem by re-installing fonts. That doesn't help us. Unity 4.6 still does not include the font.

**Comment by Chen-Han** [comment]
Hello, I encountered the same bug for unity 5 where text is not showing up. The screen shot above is a perfect reflection of what I have. However, I would like to get a more detailed answer as running 
`winetricks tahoma` does not work

Can you elaborate on "In PlayOnLinux install the 'tahoma' component for your Unity installation." ?

**Comment by Pendrokar** [comment]
@Chen-Han depends if you are actually using PlayOnLinux. Seems not.

By "winetricks tahoma does not work" do you mean that winetricks is not found, or the installation of "tahoma" did not help. If it is the latter than you might have Unity installed on a different prefix.

There was an error in my description(fixed) right after WINEPREFIX=(here you have to have the path to the Unity prefix folder)

**Comment by DoctorJellyface** [comment]
Just want to point out that Unity uses Tahoma as a fallback font. The real one is in core-fonts.

**Comment by Chen-Han** [comment]
@Pendrokar  I am using PlayOnLinux
I used default wine prefix I assume. 
The installation of tahoma fonts didn't work out. I also moved some font files to this directory: 

```
:~/.wine/drive_c/windows/Fonts$ ls
Arial.ttf  arial.ttf  tahomabd.ttf  Tahoma.ttf  tahoma.ttf
```

I wonder how you can choose to install the 'tahoma' component in: 
*When using PlayOnLinux - In PlayOnLinux install the 'tahoma' component for your Unity installation.*

Sorry I am very new to wine and playOnLinux, if you have any lead to how to solve it I really appreciate.

**Comment by DoctorJellyface** [comment]
Try lookking at this: http://wiki.playonlinux.com/index.php/The_Configuration_Window#.284.29_-_Install_Components_tab
