### ISSUE TITLE
Unity doesn't work in a 64 bit Wineprefix

### ISSUE THREAD

**Issue by jurf** [Unity3D-Wine-Support/Unity3D-on-Wine#21]
Tested in a fresh, clean 64 bit wineprefix.

Only other commands were the registry fix & the mkdir -p thing.

Crashes with "Couldn't initialize license system".

We should fix this before Unity 5.

**Comment by DoctorJellyface** [comment]
As of Wine 1.7.35, Unity correctly launches in a 64 bit wineprefix. Test it yourself with the unity3d_minimal script.

**Comment by Pendrokar** [comment]
"correctly" or "currently"? If it is the former, it should do so only for Unity 5.

**Comment by DoctorJellyface** [comment]
**Correctly**. I tested Unity 4.6.1, works without problems, only thing that went wrong is that it printed this message into the console:

    Your 64 bit Windows installation is missing an important service pack patch. Please apply http://support.microsoft.com/kb/976038 to ensure stability.

I don't have a Pro license, so I can't test Unity 5 Beta.

**Comment by Gooberpatrol66** [comment]
Are you planning on updating unity3d_minimal to v5? The full script still contains things that crash under 64bit.

**Comment by cupcakecool** [comment]
i need help i got unity from POL but if i try to open it it says error initializing license system i have tried installing it 5 times im on linux mint 17.1 so rebecca what do i do thats wrong have other people had this and fixed it? pls help

**Comment by Pendrokar** [comment]
@cupcakecool Try installing Unity in the normal way using the latest official Wine version. So you are saying that you receive an error, not a crash? The license crash issue is #13

**Comment by DoctorJellyface** [comment]
You probably have an outdated Wine, and the PoL script doesn't work-around known Wine bugs. Running `wine reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion" /v ProductId /t REG_SZ /d 12345-oem-0000001-54321` should make it work.

**Comment by cupcakecool** [comment]
but which is the up todate wine? is it the top cause i got that one i have too right now the one i came with one do i delete the older one?

**Comment by cupcakecool** [comment]
its says wine mono installer?
