### ISSUE TITLE
unity3d.verb - Tahoma font can't be downloaded

### ISSUE THREAD

**Issue by shottedsheriff** [Unity3D-Wine-Support/Unity3D-on-Wine#27]
Hallo! Great work about unity3d.verb! But there's a problem, it can't download tahoma32.exe from desired location. I had to manually download it from somewhere else. Could you resolve this problem for future fellow Linux Unity users :)?

**Comment by DoctorJellyface** [comment]
Closing this. Fixed upstream, and working around something which is supposed to be used for working _other_ things around doesn't seem like a good idea. Anyway, as far as I know, only 'Buntus suffer from this issue.

Thanks @AlbertoOS, great one-liner.

**Comment by i30817** [comment]
You can just wget the lastest version of winetricks and use that after chmod
wget http://winetricks.org/winetricks ;  chmod +x ./winetricks ;  ./winetricks -q "./unity3d.verb"

**Comment by KevWright** [comment]
If anyone wants to use @AlbertoOS suggestion, but has issues with MS' ftp like I did, the following modification seems to work:

wget http://download.microsoft.com/download/office97pro/fonts/1/w95/en-us/tahoma32.exe && mv tahoma32.exe ~/.cache/winetricks/tahoma/

**Comment by shrx** [comment]
@KevWright 's answer worked for me.
