### ISSUE TITLE
Unity 5 beta: no text visible

### ISSUE THREAD

**Issue by dnaumov** [Unity3D-Wine-Support/Unity3D-on-Wine#34]
Unity 5 installs and runs just fine on openSUSE 13.2, except that there is empty space instead of text in the editor. I guess it's basically the same issue as #18, but installing Tahoma doesn't help it.

**Comment by thediamondgames** [comment]
I solved the issue by installing 1.7.33-WGL-ShareList in PlayOnLinux. If you are not using POL, here's link to download the compiled x86 1.7.33-WGL-ShareList wine: http://www.playonlinux.com/wine/binaries/linux-x86/PlayOnLinux-wine-1.7.33-WGL-ShareList-linux-x86.pol

**Comment by DoctorJellyface** [comment]
Great!

**Comment by Radivarig** [comment]
If you don't see any text you might want to try adding Arial.TTF to `~/.wine/drive_c/windows/Fonts/Arial.TTF`
This worked for me on Unity 4.x

**Comment by DoctorJellyface** [comment]
Just tried Unity 5, works without issue. Please reopen this if it happens again.
