### ISSUE TITLE
Unity Window not showing text

### ISSUE THREAD

**Issue by bmontgom** [Unity3D-Wine-Support/Unity3D-on-Wine#46]
Menus, including context menus show text. Everything else however, does not display text. Am I missing a font installation or something? Many thanks for the support!

![screenshot from 2015-05-01 22 37 03](https://cloud.githubusercontent.com/assets/3969034/7439823/ef0c24f2-f052-11e4-9229-17ad97e23de7.png)

As you can see from the image, there is no text being displayed anywhere except for the menu bar at the top. 

This image shows that the context menu is displaying correctly.
![screenshot from 2015-05-01 22 40 13](https://cloud.githubusercontent.com/assets/3969034/7439825/0b5fe8d2-f053-11e4-956a-1ccb507391f6.png)

Any help would be greatly appreciated!

**Comment by Radivarig** [comment]
Have you seen #34 ?

Try adding Arial.TTF to
`~/.wine/drive_c/windows/Fonts/Arial.TTF`

**Comment by DoctorJellyface** [comment]
What did you use to install Unity?

Looks like you're missing Tahoma or corefonts. I would install both.

With Winetricks you can do it like so: `WINEPREFIX=~/wherever-your-wineprefix-is winetricks tahoma corefonts`.

**Comment by bmontgom** [comment]
@Radivarig that fixed the issue. Thank you! I should note that there actually was already a file named "Arial.ttf" in there but I replaced it with the one I downloaded and that worked. I don't really understand why that worked, but it did. Thank you!
