### ISSUE TITLE
Unity window renders garbage

### ISSUE THREAD

**Issue by gandalf3** [Unity3D-Wine-Support/Unity3D-on-Wine#49]
The main unity window and any subwindows render random bits from other parts of the screen, with a little bit of unity's interface occasionally mixed in. The installer, open project screen, loading dialog, and file edit assets etc. menus seem to work okay.

Clicking on random bits of the window will sometimes make popups and such appear, so it seems to be just a graphical issue.

Archlinux, x86-64, Nvidia GTX 460, proprietary drivers
Tested with the PoL script and with the winetricks script, using wine 1.7.42 and 1.7.35
Same thing happens with both Unity 1.4.x and 1.5.x

![examp627](https://cloud.githubusercontent.com/assets/11167504/7597911/9de804e0-f8ab-11e4-8e46-fd3cda3deacf.png)

**Comment by Pendrokar** [comment]
@DoctorJellyface 
gandalf3 fixed it by just installing with plain Wine. I will make a note in the wiki that people should try installing with plain Wine. Or a script that only installs Tahoma font.

"Same thing happens with both Unity 1.4.x and 1.5.x"
Probably meant 4.x and 5.x

**Comment by joshramsbottom** [comment]
Hello

I have exactly the same hardware as gandalf3 and am experiencing the same problem. Could you explain how to install with just plain Wine?

Thank you

**Comment by gandalf3** [comment]
@joshramsbottom Run the installer with wine directly:

    wine ~/path/to/unity-installer.exe

You may want to create a fresh wineprefix if you want to be sure that it won't interfere with anything else you may have installed, but I just used the default (`~/.wine`) and it's working fine for me.

You'll [have to](https://github.com/Unity3D-Wine-Support/Unity3D-on-Wine/issues/18) install the Tahoma font manually, or define a font  override.
I'm not sure how to install it "properly".. I just copied the `Tahoma*` files I found in a PoL wineprefix to `$WINEPREFIX/drive_c/windows/Fonts/` and it worked.

I did have some problems with sound, which I fixed by installing [this version of wine](https://aur.archlinux.org/packages/wine-multimedia/) from my distro's user repository.

**Comment by joshramsbottom** [comment]
@gandalf3 thank you for your swift reply. I have tried everything you said and I am still getting the same issue. Even tried reinstalling wine and recreating the default wine prefix. I am also using Arch Linux x86_64 with an NVIDIA 460 and proprietary drivers.

**Comment by gandalf3** [comment]
@joshramsbottom 

Huh.. I'm afraid I don't really know why that is..

Here's exactly what I remember doing:

1. Re-making the default `~/.wine` prefix as a 64 bit prefix. To do this I deleted `~/.wine` and then ran  
  `WINEPREFIX=~/.wine WINEARCH='win64' wine 'wineboot'`
1. Running the unity 5.0.1 installer with the version of wine the main repos (`1.7.42` atm)
1. Running unity with `wine ~/.wine/drive_c/Program\ Files/Unity/Editor/Unity.exe`. Worked fine except for sound.
1. Installing the `wine-multimedia` package to fix sound (and uninstalling `wine-gecko` because of dependency conflict).

**Comment by joshramsbottom** [comment]
@gandalf3 

Thank you so much for your help. I think setting my WINEARCH=win32 was causing problems as changing it to win64 seemed to fix it.

**Comment by DoctorJellyface** [comment]
Also, you needn't use `WINEARCH=win64`, that's uses automatically. You can also use `winetricks corefonts tahoma` to install fonts into the default prefix.
