### ISSUE TITLE
Unity Asset Store window is in plain gray/black color

### ISSUE THREAD

**Issue by Pendrokar** [Unity3D-Wine-Support/Unity3D-on-Wine#5]
Reported by all, that the Asset store window/tab shows up gray, but some elements on the window are picked up judging from that the mouse cursor changes. Some believe it is a WebKit issue and requires corrections in the Windows Registry of the Wine prefix. We are still waiting on what these people did to fix this...

["Asset Store Look and Working (WebKit Patching for Wine)"](http://forum.unity3d.com/threads/unity3d-on-linux-with-wine-support-thread.211059/page-3#post-1521195) (No other information)

WineHQ bug report - http://bugs.winehq.org/show_bug.cgi?id=34039

**Comment by dementedhedgehog** [comment]
Dusty Monks solution worked for me.

**Comment by tr37ion** [comment]
Did you all fill out your profile address information (normal browser) before you tried to download assets?

**Comment by devenv** [comment]
Not sure what you mean by that, but in my case I work under the same account on windows in parallel (downloading assets obviously)...

**Comment by Radivarig** [comment]
@devenv , what do you mean?

**Comment by DoctorJellyface** [comment]
@devenv @Radivarig I think that @tr37ion is talking about filling out the profile info using the normal Unity website, though it's down ATM - should be online in a mo, they're talking about new "game-changing" technologies, looks interesting. It might mean a Linux editor!

**Comment by devenv** [comment]
I meant - yes :)
Would be awesome @DoctorJellyface...

**Comment by devenv** [comment]
Asset store works fine in Unity5 now :)
Everything else... not really...
Any idea what fonts do they use so they won't show up? Also the scene is almost completely empty...

**Comment by DoctorJellyface** [comment]
@devenv, tried Unity 5, fonts work normally. Please refer to #34 and #16.

Anyway, the Asset Store really works now! Way to go!

**Comment by devenv** [comment]
Yep, using 1.7.33-WGL-ShareList wine version worked like a charm...
Thanks :)

**Comment by DoctorJellyface** [comment]
Caveat emptor. Two major fixes for Unity functionality under Wine landed in 1.7.34, so you might want to ask the devs to create a new patched Wine.
