### ISSUE TITLE
help me with unity for playonlinux

### ISSUE THREAD

**Issue by cupcakecool** [Unity3D-Wine-Support/Unity3D-on-Wine#54]
hello i have tried to download unity for awhile for about 5 to 8 times cause of this when i try to open it says error with initializing its license system and now it says after it says that 
this application failed to start because it could not find or load the Qt platform plugin windows it says it reinstall it may fix but its the same is there something i have to do? im on linux mint 17.1

**Comment by Pendrokar** [comment]
See comment in #13 https://github.com/Unity3D-Wine-Support/Unity3D-on-Wine/issues/21#issuecomment-109198254

**Comment by DoctorJellyface** [comment]
You probably have an outdated Wine, and the PoL script doesn't work-around known Wine bugs. Running `wine reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion" /v ProductId /t REG_SZ /d 12345-oem-0000001-54321` should make it work.

**Comment by cupcakecool** [comment]
but i didnt use the script i just downloaded it with unity site and chose a file to cover it with POL like i followed him to do but using a script i did that once it didnt use it cause it said wrong one

**Comment by cupcakecool** [comment]
but what wine should i use?

**Comment by DoctorJellyface** [comment]
Preferably the newest one, staging if you want OpenGL.

Did you try the command?

**Comment by cupcakecool** [comment]
no not yet so i install it again with the script

**Comment by cupcakecool** [comment]
so i used the script so you have to download something? it said its not a vaild script is this normal?

**Comment by cupcakecool** [comment]
ok you can just tell me what to do in a full comment that is best

**Comment by DoctorJellyface** [comment]
Yes. It's not signed by the PoL team. Although the script is obsolete, you can find a new version in #50.

It would be easier to use the winetricks script right now, or even updating Wine and installing manually.

What distro are you running?

**Comment by cupcakecool** [comment]
distro? for like kind of linux? if so linux mint the newst one so 17.1

**Comment by DoctorJellyface** [comment]
Please follow these instructions: https://github.com/wine-compholio/wine-staging/wiki/Installation#-ubuntulinux-mint

After that, just manually install Unity. No, PoL, no winetricks, no scripts.

It should work just fine.

**Comment by cupcakecool** [comment]
thanks :) this will be helpful me and my friend will make a horror game and did you do this?

**Comment by DoctorJellyface** [comment]
Yeah, my current setup is installed this way, just on Arch linux.

Good luck with your game :)

**Comment by cupcakecool** [comment]
thanks :) so i run that in thermal then i install right? i just want to make sure cause sometimes it can be hard for me to follow stuff and dont want to mess up

**Comment by DoctorJellyface** [comment]
*terminal

The wine installation yes. But you can do the Unity installation from the GUI.

**Comment by cupcakecool** [comment]
ok but asking dumbly sorry but it doesnt say which one do i do any? or just the vary top

**Comment by DoctorJellyface** [comment]
Do all the commands under the ubuntu section.

**Comment by cupcakecool** [comment]
im so sorry but where is that? 
sorry im not a PC tech person like you :)

**Comment by DoctorJellyface** [comment]
OK, type this into your terminal (tip: you can paste stuff into the terminal with `Ctrl+Shift+V`:

`sudo add-apt-repository ppa:pipelight/stable`

Then:

`sudo apt-get update`

After that:

`sudo apt-get install --install-recommends wine-staging`

And finally:

`sudo apt-get install wine-staging-compat`

Now you can just double click on your Unity installer from your file manager.

**Comment by cupcakecool** [comment]
ok thanks but i can use Pol for this so i type it in and then just install by Pil

**Comment by cupcakecool** [comment]
*pol

**Comment by cupcakecool** [comment]
ok i put that in  terminal then i went into files like you said then i clicked on this so called unity download asstaint and it started downloading so i did this right?

**Comment by cupcakecool** [comment]
but in terminal after i pasted it kept saying command not found is that right?

**Comment by cupcakecool** [comment]
i am sorry for dumb things the only thing i can do with  PCs is wipe hard drives causing my screen/ PC wont turn on but i can fix that etc

**Comment by cupcakecool** [comment]
but its still the same

**Comment by cupcakecool** [comment]
it still says the same thing

**Comment by DoctorJellyface** [comment]
Closing in favour of #59.
