### ISSUE TITLE
please help some more

### ISSUE THREAD

**Issue by cupcakecool** [Unity3D-Wine-Support/Unity3D-on-Wine#55]
so i made another one but i tried doing this one from one guy but it didnt work did i do something wrong? i dont know if you are new to my problem its if i try to download unity from playonlinux A.K.A Pol if i open it it says error initializing license system then after it says unity failed to start cause it could not find or load the Qt platform plugin! what does this mean?!? im on linux mint 17.1 my wine versions are 1.7.44 staging what wine version do i need? or what do i need to do with unity please reply

**Comment by DoctorJellyface** [comment]
Closing in favour of #59.

**Comment by cupcakecool** [comment]
is the Qt thing a plugin how do i get it or what do i do?
