### ISSUE TITLE
Altgr doesn't work

### ISSUE THREAD

**Issue by Amadren** [Unity3D-Wine-Support/Unity3D-on-Wine#57]
Hi,
AltGr + Key doesn't work on Unity's monodevelop. For exemple, wen I press "Altgr" + "+" on my keyboard, it should writ "}" but it writes "+". Using a french, azerty keyboard.

**Comment by DoctorJellyface** [comment]
Hey, thanks for taking time to report this, but it was already reported in #37. However please feel free to report any other bugs you find.
