### ISSUE TITLE
Unity windows not show any ting ...

### ISSUE THREAD

**Issue by hamidwairless** [Unity3D-Wine-Support/Unity3D-on-Wine#60]
Hi, any body can Help me ...

![screenshot from 2015-06-23 11 34 39](https://cloud.githubusercontent.com/assets/13013123/8301094/46b41180-19a0-11e5-8b76-2301f1fc14c5.png)
![screenshot from 2015-06-23 11 35 19](https://cloud.githubusercontent.com/assets/13013123/8301095/46de5184-19a0-11e5-986e-70b203096b18.png)

**Comment by hamidwairless** [comment]
I update my wine ... it's now is good working ... 

![screenshot from 2015-06-23 04 40 59](https://cloud.githubusercontent.com/assets/13013123/8302301/60ea0682-1963-11e5-8e01-f0b2becef642.png)

**Comment by DoctorJellyface** [comment]
Great!
