### ISSUE TITLE
Service not available, please try again later

### ISSUE THREAD

**Issue by CyanBlob** [Unity3D-Wine-Support/Unity3D-on-Wine#62]
When running unity3d.verb (32bit wineprefix) with the Unity 5.0.2 installer, there was a problem downloading Unity (it would download to something like 175%, then say it couldn't verify the file integrity), so I modified the file to use the latest Unity 5.1.1 installer, ran    
`wine reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion" /v ProductId /t REG_SZ /d 12345-oem-0000001-54321`

to allow Unity to get past the license window (from https://github.com/Unity3D-Wine-Support/Unity3D-on-Wine/issues/13)
Now, Unity installed properly, but I can't get past the log in screen. It says "Service not available, please try again later" when I click the log in button. I've installed IE8 in the same wineprefix (or I believe I did, my experience with wine is very minimal)
Does anyone have a solution/debugging steps I should take?
I'm running 64bit Linux Mint 17.2 Cinnamon, using wine 1.6.2
Let me know if you need any more information, and I will try to get it for you quickly.

![screenshot from 2015-07-14 18 20 46](https://cloud.githubusercontent.com/assets/5949523/8687362/1aa0d39c-2a55-11e5-8f2a-15096aa39c4d.png)

**Comment by DoctorJellyface** [comment]
Wipe your prefix, update your Wine (preferably to staging) and install again with the modified script. You can get the checksums of the newer installer by running `sha1sums /path/to/UnitySetup.exe`.

**Comment by CyanBlob** [comment]
Reinstall did not work. As the beta release of Unity3d seems right around the corner, I'll just hold off.

**Comment by DoctorJellyface** [comment]
Hm. Strange. Though don't rely on the Unity beta, it'll probably be more than a month until they push it out to the public. They've only released one build to this date.

**Comment by CyanBlob** [comment]
If anyone comes across this, updating to wine 1.7.49 fixed my problem! 1.7.46 did not. So hopefully this will help somebody.

**Comment by DoctorJellyface** [comment]
Cool!
