### ISSUE TITLE
The future of the Unity Support Team

### ISSUE THREAD

**Issue by jurf** [Unity3D-Wine-Support/Unity3D-on-Wine#64]
As you all probably know, a **native Unity Linux Editor** is in the works. I have been accepted into early testers team (yay!), so I'll get the builds early.

But the point is that after the editor will be released, there will be almost no need for this repository. I might maintain it for a bit longer, but probably not for long. If anyone wants to keep mainaining this (except for the current maintainers), please leave a reply.

Thanks.

**Comment by ElijahLynn** [comment]
Congrats on being accepted to the testers team!! How are the alpha builds looking? Major hurdles or fairly trivial issues remaining?

**Comment by DoctorJellyface** [comment]
Only just got it today. So far a lot of crashes, some minor mistakes but it looks like the next build will be much better.

Though they haven't read my report yet, hehe.

I'll write more about it tommorow. Spent today packaging it for Arch.

**Comment by ElijahLynn** [comment]
Thanks for the update!

**Comment by ElijahLynn** [comment]
Experimental build just released!! 

https://twitter.com/natosha_bard/status/636494408884600832

**Comment by jurf** [comment]
So yeah, the Linux Editor is alive and functioning and this team is dead. Closing. It’s been a good ride, thanks for everything.
