### ISSUE TITLE
Can't  find character controller package in unity.

### ISSUE THREAD

**Issue by cupcakecool** [Unity3D-Wine-Support/Unity3D-on-Wine#65]
Okay so i finally got unity in linux mint. But i can't find the character controller or first/third person controller. And in the asset store i cant find it or something thats free. Can someone help me with this? I have tried finding stuff online but nothing fixed my problem.

**Comment by DoctorJellyface** [comment]
@cupcakecool keep in mind that this place is only meant for Wine support, so I'm closing this. You'll need to look elsewhere, there's tons of locations where there are answers to you Unity questions.

As far as I know, Standard Aseets were removed in 5.0. You can find others in the Asset Store just by searching. You can see the "made by Unity" in the right sidebar.
