### ISSUE TITLE
Invalid Unity download URL

### ISSUE THREAD

**Issue by danheidel** [Unity3D-Wine-Support/Unity3D-on-Wine#69]
I haven't had any luck completing the install via either the POL script or winetricks script.  When I run winetricks, I get the following error:

    Downloading http://netstorage.unity3d.com/unity/0b02744d4013/UnityDownloadAssistant-5.0.2f1.exe to /home/dan/.cache/winetricks/unity3d
    --2015-08-31 22:25:14--  http://netstorage.unity3d.com/unity/0b02744d4013/UnityDownloadAssistant-5.0.2f1.exe
    Resolving netstorage.unity3d.com (netstorage.unity3d.com)... 23.59.190.112, 23.59.190.120
    Connecting to netstorage.unity3d.com (netstorage.unity3d.com)|23.59.190.112|:80... connected.
    HTTP request sent, awaiting response... 404 Not Found
    2015-08-31 22:25:15 ERROR 404: Not Found.
    
    ------------------------------------------------------
    Downloading http://netstorage.unity3d.com/unity/0b02744d4013/UnityDownloadAssistant-5.0.2f1.exe failed
    ------------------------------------------------------

**Comment by DoctorJellyface** [comment]
Hm, looks like the old installer no longer exists on the server. You'll have to manually update the script. Just look at any of the update commits, it's pretty straighforward.

Also, why don't you just use the native editor?

**Comment by danheidel** [comment]
Editing the script is straightforward but I have no idea how to get an up-to-date download URL or what I assume is the SHA1 checksum hash appended to the URL in the script.

Also, what's the native editor?  The forum threads I read made it look like that was still in closed alpha/beta.

**Comment by spacepluk** [comment]
The published an experimental build :)

http://forum.unity3d.com/threads/unity-on-linux-release-notes-and-known-issues.350256/

**Comment by danheidel** [comment]
Ah thanks!  That worked perfectly!
