### ISSUE TITLE
Unity requires windows 7 or later!

### ISSUE THREAD

**Issue by ashokbugude** [Unity3D-Wine-Support/Unity3D-on-Wine#77]
I am trying to install unity in linux .But I get attached popup after below steps are executed in terminal
$ winetricks ./unity3d.verb
Executing w_do_call unity3d
Executing load_unity3d
Executing w_do_call tahoma
tahoma already installed, skipping
Executing w_do_call corefonts
corefonts already installed, skipping
------------------------------------------------------
Now running the Unity installation. As Unity is very big, this can take more than 20 minutes. Please be patient.
------------------------------------------------------

If I click ok and continue, I get below message in terminal at the end
unity3d install completed, but installed file /home/ashok/.local/share/wineprefixes/unity3d/dosdevices/c:/Program Files/Unity/Editor/Unity.exe not found
![popup](https://cloud.githubusercontent.com/assets/10016848/14593789/b328153a-054c-11e6-918f-43bd7b8deeeb.png)

**Comment by SkelEloren** [comment]
Had the same issue, solved by adding
`Set_OS "win7"` 
to the .pol script. According to the PlayOnLinux scripting guide, it has to be after creating prefixes. So the final file should look like:
<pre><code># Create the prefix
POL_Wine_SelectPrefix "$PREFIX"
#Set OS Version
Set_OS "win7"
</code>
</pre>

**Comment by ashokbugude** [comment]
Thanks Working Fine

**Comment by Radivarig** [comment]
Any way of setting OS for wine only, without playonlinux?
