### ISSUE TITLE
"Beast" lightmapping engine crashes Unity on lightmap baking

### ISSUE THREAD

**Issue by Pendrokar** [Unity3D-Wine-Support/Unity3D-on-Wine#9]
To reproduce - Bake a single object with "Single Lightmap" mode.

WineHQ bug report - http://bugs.winehq.org/show_bug.cgi?id=36976

**Comment by Pendrokar** [comment]
Could someone test if this is still an issue for Unity 5?

**Comment by DoctorJellyface** [comment]
Unity 5 no longer uses Beast, closing.
